# Set Ghostty as default terminal
- name: Register Ghostty snap binary with update-alternatives
  ansible.builtin.command:
    cmd: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /snap/bin/ghostty 100

- name: Set Ghostty as the default terminal emulator
  ansible.builtin.command:
    cmd: update-alternatives --set x-terminal-emulator /snap/bin/ghostty

